DjangoGramm/urls.py
from django.contrib import admin
from django.urls import path, include

from DjangoGramm import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from DjangoGramm import settings
from .views import *



app_name = 'app'

urlpatterns = [
    path('followers/', followers, name='followers'),
    path('following/', following, name='following'),
    path('subscribe/', subscribe, name='subscribe'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('registration/', signup, name='registration'),
    path('add_content/', add_content, name="add_content"),
    path('', view_content, name="view_content"),
    path('view_content/<str:content>', post, name="view_post"),
    path('view_profile/<str:username>/', view_profile, name="view_profile"),
    path('tag/', tag, name="tag"),
    path('view_tag/', view_tag, name="view_tag"),
    path('like/', like_content, name="like_content"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
    path('profile/create_user_profile', profile, name='create_user_profile'),
    ]

app/templates/profile/create_user_profile.html
{% extends 'base.html' %}

{% block title %}
Profile Page
{% endblock title %}


{% block static %}
{% load static %}
<link rel="stylesheet" href="{% static 'app/css/signup.css' %}">
{% endblock %}

{% block content %}
<h2>Please fill in the data</h2>

    <h4><div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">

                        <label class="small mb-1">Biography:</label>
                            {{ profile_form.description }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.user_image }}
                    </div>
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-outline-warning">Save Changes</button>
            <button type="reset" class="btn btn-outline-warning">Reset</button>
        </form>
    </div></h4>
{% endblock content %}

app/templates/profile/profile.html
{% extends 'head.html' %}

{% block title %}
My profile
{% endblock title %}

{% block static %}
{% load static %}
<link rel="stylesheet" href="{% static 'app/css/signup.css' %}">
{% endblock %}

{% block head %}
{% if user == user_login %}
<div style='margin-left:32px;'>
 <form action="{% url 'app:create_user_profile' %}" method="POST">
     {% csrf_token %}
     <input type="hidden" name="change_profile" value="True"><button type="submit" class="btn btn-outline-warning">Change profile: {{ user_login.username }}</button>
 </form>
</div>
{% endif %}

{% if user != user_login %}
<form id="sub">
    {% csrf_token %}
<div>
   {% if user_login not in sub_user %}
<button type="button" id="status_sub" name="{{user_login.id}}" class="rounded-3" style="font-size:20px; color:black; background-color: #4CAF50;">Subscribe</button>
    {% else %}
<button type="button" id="status_sub" name="{{user_login.id}}" class="rounded-3"  style="font-size:20px; color:black; background-color: #f44336;">Unsubscribe</button>
    {% endif %}
  </div>
</form>{% endif %}
<ul class="rounded float-start">
  <p><img class="rounded-3" width="500" height="302" src="{{ profile.user_image.url }}"></p>
</ul>

<h3><div style='margin-left:550px;'>
 Nickname: {{ user_login.username }}
<br><br>
 Biography: {{ profile.description }}
<br><br>
</h3>
</div>
{% if user == user_login %}
<div style='margin-left:550px;'>
 <form action="{% url 'app:following' %}" method="POST">
     {% csrf_token %}
       <input type="hidden" name="following" value="True"><button type="submit" class="btn btn-outline-warning">Following</button>
   </form>
</div>
<div style='margin-left:660px; margin-top:-37px;'>
   <form action="{% url 'app:followers' %}" method="POST">
       {% csrf_token %}
       <input type="hidden" name="followers" value="True"><button type="submit" class="btn btn-outline-warning">Followers</button>
   </form>
</div>
<div style='margin-left:550px;'>
<form action="{% url 'app:add_content' %}" method="POST">
    {% csrf_token %}
       <input type="hidden" name="add_content" value="True"><button type="submit" class="btn btn-outline-warning">Add content</button>
   </form>
</div>
{% endif %}

</html>
<h3><div style='margin-left:35px; margin-top:133px;'>
{% if user == user_login %}
<br><br>
My publications:
<br><br>
{% else %}
<br><br>
    {{user_login.username}} publications:
<br><br>
{% endif %}

{% for content in content_all %}
<a href="/view_content/{{content.id}}"><img class="rounded-3" width="300" height="201" src="{{ content.content_id.first.image.url }}" ></a>
{% endfor %}

</h3></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
// AJAX CALL
$('.rounded-3').click(function(){
    $.ajax({
             type: "POST",
             url: "{% url 'app:subscribe' %}",
             data: {'subscribe_user': $(this).attr('name'),'csrfmiddlewaretoken': '{{ csrf_token }}'},
             dataType: "json",
             success: function(response) {
                    if(response.subscribe==true){
                      $("#status_sub").css("background-color","#f44336");
                      $("#status_sub").text('Unsubscribe');

                    }
                    else if(response.subscribe==false){
                      $("#status_sub").css("background-color","#4CAF50");
                      $("#status_sub").text('Subscribe');

                    }
              }
        });
  })
</script>

{% endblock head %}