DjangoGramm/urls.py
from django.contrib import admin
from django.urls import path, include

from DjangoGramm import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from DjangoGramm import settings
from .views import *



app_name = 'app'

urlpatterns = [
    path('followers/', followers, name='followers'),
    path('following/', following, name='following'),
    path('subscribe/', subscribe, name='subscribe'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('registration/', signup, name='registration'),
    path('add_content/', add_content, name="add_content"),
    path('', view_content, name="view_content"),
    path('view_content/<str:content>', post, name="view_post"),
    path('view_profile/<str:username>/', view_profile, name="view_profile"),
    path('tag/', tag, name="tag"),
    path('view_tag/', view_tag, name="view_tag"),
    path('like/', like_content, name="like_content"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
    path('profile/create_user_profile', profile, name='create_user_profile'),
    ]

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
      <link rel="stylesheet" href="{% static '/app/bootstrap.min.css' %}">
     <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    {% block static %}{% endblock %}
  </head>
  <body>
   {% block content %}
   {% endblock content %}
   </body>
   </html>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

 </body>
</html>

app/templates/head.html
{% extends 'base.html' %}

{% block content %}

  <nav class="navbar bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
      <a class="btn btn-outline-warning" href="http://127.0.0.1:8000/view_profile/{{user.username}}/">
          My profile
    </a>
      <ul class="nav justify-content-end">
          <li class="nav-item">
      <a class="btn btn-outline-warning" href="http://127.0.0.1:8000">
          Home
    </a>
          </li>
     <li class="nav-item">
    <form action="{% url 'app:logout' %}">
    <button type="submit" class="btn btn-outline-warning">Logout</button>
    </form>
          </li>
      </ul>
    </div>
</nav>

{% block head %}
{% endblock %}
{% endblock content %}